### ISSUE TITLE
Axios Cross-Site Request Forgery Vulnerability

### ISSUE THREAD

**Issue by lgiannini1** [US-EPA-CAMD/easey-campd-ui#619]
Moderate Dependabot Issue in the following repos

https://github.com/US-EPA-CAMD/easey-campd-ui/security/dependabot/56

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec942de3b34b89aeb82bb48d353631ffdeb0f667/Capture.PNG

**Comment by annalbrecht** [comment]
This has been resolved.
