### ISSUE TITLE
HSTS - HTTP Strict Transport Security headers mandate for all applications by default. 

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/easey-campd-ui#627]
As per the (HSTS) Security update mandate and based on the report provided by EPA, we need to implement this requirement for all domains/subdomains on/before 1/26 per @maheese & @tlageman-epa.

**Comment by annalbrecht** [comment]
Max age needs to be set to the default-- 1 year-- as opposed to 6 months.

**Comment by annalbrecht** [comment]
Deployed.
